# Download
[[main]]
  name = "Download"
  identifier = "download"
  weight = 10
  url = "docs/downloads/latest"

# News
[[main]]
  name = "News"
  identifier = "news"
  weight = 15
  url = "blog"
  
# Android
[[main]]
  name = "Android"
  identifier = "android"
  weight = 20
  url = "https://android.moneymanagerex.org/?utm_medium=Website_MoneyManagerEX&utm_source=Menu"

# Support
[[main]]
  name = "Support"
  identifier = "support"
  weight = 30
[[main]]
  name = "Documentation"
  identifier = "documentation"
  parent = "support"
  url = "https://moneymanagerex.org/moneymanagerex/"
  weigth = 1
[[main]]
  name = "Forum"
  identifier = "forum"
  parent = "support"
  url = "https://forum.moneymanagerex.org/?utm_campaign=Website_MoneyManagerEX&utm_medium=Website_MoneyManagerEX&utm_source=Menu"
  weight = 2
[[main]]
  name = "Slack"
  identifier = "slack"
  parent = "support"
  url = "http://slack.moneymanagerex.org/"
  weight = 3
[[main]]
  name = "Wiki"
  identifier = "wiki"
  parent = "support"
  url = "https://github.com/moneymanagerex/moneymanagerex/wiki"
  weight = 4
[[main]]
  name = "Report a Bug"
  identifier = "bug"
  parent = "support"
  url = "https://github.com/moneymanagerex/moneymanagerex/labels/bug"
  weight = 5
[[main]]
  name = "Feature Request"
  identifier = "featurereq"
  parent = "support"
  url = "https://github.com/moneymanagerex/moneymanagerex/labels/feature"
  weight = 6
[[main]]
  name = "Donate"
  identifier = "doante"
  parent = "support"
  url = "docs/mmex/donate"
  weight = 7

# Development
[[main]]
  name = "Development"
  identifier = "development"
  weight = 40
[[main]]
  name = "Changelog"
  identifier = "changelog"
  parent = "development"
  url = "https://github.com/moneymanagerex/moneymanagerex/releases"
  weight = 1
[[main]]
  name = "Source Code"
  identifier = "sourcecode"
  parent = "development"
  url = "https://github.com/moneymanagerex"
  weight = 2
[[main]]
  name = "Translations"
  identifier = "translate"
  parent = "development"
  url = "https://crowdin.com/project/moneymanagerex"
  weight = 3
[[main]]
  name = "Donate"
  identifier = "donate"
  parent = "development"
  url = "docs/mmex/donate"
  weight = 4
[[main]]

# About
[[main]]
  name = "About"
  identifier = "about"
  weight = 50
[[main]]
  name = "Donate"
  identifier = "donate"
  parent = "about"
  url = "docs/mmex/donate"
  weight = 1
[[main]]
  name = "Contributors"
  identifier = "contributors"
  parent = "about"
  url = "docs/mmex/contributors"
  weight = 2
[[main]]
  name = "Press Reviews"
  identifier = "press"
  parent = "about"
  url = "docs/mmex/press"
  weight = 3
[[main]]
  name = "License"
  identifier = "license"
  parent = "about"
  url = "docs/mmex/license"
  weight = 4
[[main]]
  name = "Privacy"
  identifier = "privacy"
  parent = "about"
  url = "docs/mmex/privacy"
  weight = 5


[[social]]
  name = "GitHub"
  pre = "<i class=\"fa-brands fa-github\"></i>"
  url = "https://github.com/moneymanagerex/moneymanagerex"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<i class=\"fa-brands fa-twitter\"></i>"
  url = "https://twitter.com/moneymanagerex"
  weight = 20

[[social]]
  name = "YouTube"
  pre = "<i class=\"fa-brands fa-youtube\"></i>"
  url = "https://www.youtube.com/user/moneymanagerex"
  weight = 30

[[social]]
  name = "Facebook"
  pre = "<i class=\"fa-brands fa-facebook\"></i>"
  url = "https://www.facebook.com/MoneyManagerEx"
  weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
